//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOR_WS.QRGenerator {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QRGenerator.IQRGenerator")]
    public interface IQRGenerator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQRGenerator/GenerateQRCode", ReplyAction="http://tempuri.org/IQRGenerator/GenerateQRCodeResponse")]
        string GenerateQRCode(string Data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQRGenerator/GenerateQRCode", ReplyAction="http://tempuri.org/IQRGenerator/GenerateQRCodeResponse")]
        System.Threading.Tasks.Task<string> GenerateQRCodeAsync(string Data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQRGeneratorChannel : BOR_WS.QRGenerator.IQRGenerator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QRGeneratorClient : System.ServiceModel.ClientBase<BOR_WS.QRGenerator.IQRGenerator>, BOR_WS.QRGenerator.IQRGenerator {
        
        public QRGeneratorClient() {
        }
        
        public QRGeneratorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QRGeneratorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QRGeneratorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QRGeneratorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GenerateQRCode(string Data) {
            return base.Channel.GenerateQRCode(Data);
        }
        
        public System.Threading.Tasks.Task<string> GenerateQRCodeAsync(string Data) {
            return base.Channel.GenerateQRCodeAsync(Data);
        }
    }
}
